
###
GET    http://localhost:8099/items/all
Content-Type: application/json

{
  "name": "Maria",
  "list": ["Arroz", "Jugo natural"]
}


###
POST   http://localhost:8099/items/hola
Content-Type: application/json

{
  "name": "carlos",
  "list": ["hola", "Cover"]
}

###
PATCH    http://localhost:8099/items/2
Content-Type: application/json

{
  "name": "Jamsel",
  "list": ["Arroz", "Jugo de limon"]
}

###
DELETE   http://localhost:8099/items/2
Content-Type: application/json

{
  "name": "Maria",
  "list": ["Arroz", "Jugo natural"]
}